name: Deploy to S3
on:
  push:
    paths:
      - .github/workflows/deploy.yml
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ !github.actor == 'dependabot[bot]' }}
    environment: demo
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Debug OIDC Claims
        uses: github/actions-oidc-debugger@aa6f357e1e75bafb27d8d6528f2a02fe5c540a20
        with:
          audience: 'https://github.com/github'        

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@8c3f20df09ac63af7b3ae3d7c91f105f857d8497 # v4.0.0
        with:
            role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions/demo
            role-session-name: gh-actions
            aws-region: eu-west-1            

      - name: Create ASCII Art
        run: |
          sudo apt-get update && sudo apt-get install -y figlet
          echo "zero trust" | figlet > demo.txt

      - name: Upload to S3
        run: |
          aws s3 cp demo.txt s3://${{ vars.AWS_BUCKET_NAME }}/demo-${{ github.job }}.txt

      - name: Show content of file in s3
        run: |
          aws s3 cp s3://${{ vars.AWS_BUCKET_NAME }}/demo-${{ github.job }}.txt - | cat
